// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh7NCoLmAbGwcdNczksqAJL_ZJ_P6uIaA',
    appId: '1:861159117963:web:55d4bd7ae870d503fdf08e',
    messagingSenderId: '861159117963',
    projectId: 'limeproje',
    authDomain: 'limeproje.firebaseapp.com',
    storageBucket: 'limeproje.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU44-N6xIwwLYdLIWLdxMNS17Cey8lpyM',
    appId: '1:861159117963:android:661963d277435581fdf08e',
    messagingSenderId: '861159117963',
    projectId: 'limeproje',
    storageBucket: 'limeproje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbI40SYF77JYxXryRVl3qo4Pq0u9cY5Os',
    appId: '1:861159117963:ios:bbd0c6cc2572854cfdf08e',
    messagingSenderId: '861159117963',
    projectId: 'limeproje',
    storageBucket: 'limeproje.firebasestorage.app',
    iosBundleId: 'com.example.gasmon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbI40SYF77JYxXryRVl3qo4Pq0u9cY5Os',
    appId: '1:861159117963:ios:bbd0c6cc2572854cfdf08e',
    messagingSenderId: '861159117963',
    projectId: 'limeproje',
    storageBucket: 'limeproje.firebasestorage.app',
    iosBundleId: 'com.example.gasmon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh7NCoLmAbGwcdNczksqAJL_ZJ_P6uIaA',
    appId: '1:861159117963:web:df3c70daf07f9cdbfdf08e',
    messagingSenderId: '861159117963',
    projectId: 'limeproje',
    authDomain: 'limeproje.firebaseapp.com',
    storageBucket: 'limeproje.firebasestorage.app',
  );
}
